import "../assets/main.css"
import Footer from "../components/Footer";
import Header from "../components/Header";

export const metadata = {
  title: 'Landing Page Assignment',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <Header/>
      {children}
      <Footer/>
      </body>

      </html>
  )
}
